#' Save a ggplot2 plot to file and update file EXIF metadata
#'
#' @description
#' Save a plot or map then update the EXIF metadata for the title, author, and
#' create data. [ggsave_ext()] also supports creating a file name based on a
#' sentence case name with spaces (e.g. "Baltimore city map") and appending a
#' label (e.g. "baltcity") as a prefix to the output file name.
#'
#' [map_ggsave_ext()] can take a list of {ggplot2} plots (e.g. a list of plot
#' generated by [purrr::map()]) and create multiple files using the same
#' parameters or use the {gridExtras} package to create a single combined PDF
#' file.
#'
#' @param plot Plot to save, defaults to last plot displayed. If plot is an
#'   "magick-image" class object, it is converted to a plot using
#'   [magick::image_ggplot()]
#' @inheritParams ggplot2::ggsave
#' @param name Plot name, used to create filename (if filename is `NULL`) using
#'   [filenamr::make_filename()]
#' @inheritParams filenamr::make_filename
#' @param paper Paper matching name from `paper_sizes` (e.g. "letter"). Not case
#'   sensitive.
#' @param orientation Page orientation ("portrait", "landscape", or "square").
#' @param asp Numeric aspect ratio used to determine width or height if only one
#'   of the two arguments is provided; defaults to `NULL`.
#' @param bgcolor Background color to optionally override `plot.background`
#'   theme element.
#' @param exif If `TRUE`, the EXIF metadata for the exported file is updated
#'   with the exifr package; defaults to `FALSE`.
#' @param overwrite If `TRUE`, overwrite any existing file with the same name
#'   without asking.
#' @inheritParams sfext::write_exif
#' @param preview If `TRUE`, open saved file in default system application.
#'   Based on [tjmisc::ggpreview()].
#' @inheritDotParams ggplot2::ggsave -width -height -units -bg
#' @example examples/ggsave_ext.R
#' @seealso
#'  [ggplot2::ggsave()]
#' @rdname ggsave_ext
#' @export
#' @importFrom sfext get_paper
#' @importFrom filenamr str_extract_fileext str_remove_fileext make_filename
#'   check_file_overwrite write_exif
#' @importFrom ggplot2 ggsave
ggsave_ext <- function(plot = last_plot(),
                       name = NULL,
                       label = NULL,
                       prefix = NULL,
                       postfix = NULL,
                       filename = NULL,
                       device = NULL,
                       filetype = NULL,
                       path = NULL,
                       paper = NULL,
                       orientation = "portrait",
                       width = NULL,
                       height = NULL,
                       asp = NULL,
                       units = "in",
                       scale = 1,
                       dpi = 300,
                       bgcolor = NULL,
                       exif = FALSE,
                       title = NULL,
                       author = NULL,
                       keywords = NULL,
                       args = NULL,
                       overwrite = TRUE,
                       preview = FALSE,
                       ...) {
  if (!is.null(paper)) {
    paper <- sfext::get_paper(paper = paper, orientation = orientation)

    width <- paper$width
    height <- paper$height
    units <- paper$units
  } else if (!is.null(asp) && (is.null(width) | is.null(height))) {
    cli_abort_ifnot(
      "{.arg width} or {.arg height} must be provided if {.arg asp} is provided
      and {.code paper = NULL}.",
      condition = !is.null(width) | !is.null(height)
    )

    height <- height %||% width * asp
    width <- width  %||% height / asp
  }

  cli_abort_ifnot(
    "{.arg paper}, numeric {.arg width} and {.arg height}, or a numeric
    {.arg asp} and {.arg width} or {.arg height} must be provided.",
    condition = is.numeric(width) && is.numeric(height)
  )

  if (is.null(device) && (!is.null(filetype) | !is.null(filename))) {
    filetype <- filetype %||% filenamr::str_extract_fileext(filename)

    if (!is.null(filename)) {
      filename <- filenamr::str_remove_fileext(filename, filetype)
    }

    device <- filetype
  }

  filename <-
    filenamr::make_filename(
      name = name,
      label = label,
      filename = filename,
      fileext = filetype,
      path = path,
      prefix = prefix,
      postfix = postfix
    )

  filenamr::check_file_overwrite(filename = filename, overwrite = overwrite, ask = FALSE)

  if (inherits(plot, "magick-image")) {
    is_pkg_installed("magick")
    cli_inform(
      "Converting {.arg plot} from {.cls magick-image} to {.cls ggplot}."
    )
    plot <- magick::image_ggplot(plot)
  }

  ggplot2::ggsave(
    filename = filename,
    plot = plot,
    device = device,
    scale = scale,
    width = width,
    height = height,
    units = units,
    dpi = dpi,
    bg = bgcolor,
    ...
  )

  cli_inform(
    c("v" = "Saving {.path {filename}}.")
  )

  if (exif) {
    filenamr::write_exif(
      path = filename,
      fileext = filetype,
      title = title,
      author = author,
      keywords = keywords,
      date = NULL,
      args = args
    )
  }

  if (preview) {
    system2("open", filename)
  }
}

#' @rdname ggsave_ext
#' @name ggsave_social
#' @inheritParams sfext::get_social_image
#' @export
#' @importFrom ggplot2 last_plot
#' @importFrom rlang exec
ggsave_social <- function(plot = last_plot(),
                          image = "Instagram post",
                          platform = NULL,
                          format = NULL,
                          orientation = NULL,
                          name = NULL,
                          filename = NULL,
                          filetype = "jpeg",
                          dpi = 72,
                          width = 1080,
                          height = 1080,
                          units = "px",
                          ...) {
  image_size <-
    sfext::get_social_image(
      image = image,
      platform = platform,
      format = format,
      orientation = orientation
    )

  params <-
    modify_fn_fmls(
      params = list2(...),
      fn = ggsave_ext,
      plot = plot,
      width = image_size$width,
      height = image_size$height,
      name = name,
      filename = filename,
      filetype = filetype,
      units = units
    )

  rlang::exec(
    ggsave_ext,
    !!!params
  )
}

#' @name map_ggsave_ext
#' @rdname ggsave_ext
#' @param single_file If `TRUE`, use [gridExtra::arrangeGrob()] to create an
#'   arrangelist class object that [ggplot2::ggsave()] can save as a single
#'   multi-page file. Note: this does not work with plots modified with
#'   patchwork including inset maps created with the
#'   [layer_inset()] function.
#' @export
#' @importFrom purrr map
map_ggsave_ext <- function(plot,
                           name = NULL,
                           label = NULL,
                           prefix = NULL,
                           postfix = "pg_",
                           filename = NULL,
                           device = NULL,
                           filetype = NULL,
                           path = NULL,
                           overwrite = TRUE,
                           ...,
                           single_file = TRUE) {
  cli_abort_ifnot(
    "{.arg plot} must be a list object.",
    condition = is.list(plot)
  )

  filename <-
    filenamr::make_filename(
      name = name,
      label = label,
      filename = filename,
      fileext = filetype,
      path = NULL,
      prefix = prefix
    )

  is_patchwork_plot <- !inherits(plot, "patchwork")

  if (single_file && !is_patchwork_plot) {
    is_pkg_installed("gridExtra")

    plot <-
      purrr::map(
        seq(plot),
        ~ gridExtra::arrangeGrob(plot[[.x]])
      )

    class(plot) <- c("arrangelist", class(plot))

    ggsave_ext(
      plot = plot,
      ...
    )

    return(invisible(NULL))
  }

  path <- path %||% getwd()

  if (has_fileext(filename, "pdf") && single_file) {
    is_pkg_installed("qpdf")
    is_pkg_installed("fs")

    path <- file.path(path, "ggsave_ext_single_file_temp")

    if (fs::dir_exists(path)) {
      fs::dir_delete(path)
    } else {
      fs::dir_create(path)
    }

  } else if (single_file) {
    cli_warn("{.arg single_file} can't be used with patchwork plots unless saving a pdf file.")
    single_file <- FALSE
  }

  postfixes <- NULL
  for (pg in seq(plot)) {
    pg_postfix <- glue("{postfix}{pg}")

    ggsave_ext(
      plot = plot[[pg]],
      postfix = pg_postfix,
      filename = filename,
      path = path,
      ...
    )
  }

  if (!single_file) {
    return(invisible(NULL))
  }
  input <-
    list.files(
      path = path,
      pattern = "*.pdf"
    )

  filenamr::check_file_overwrite(
    filename = filename,
    path = path,
    overwrite = overwrite,
    ask = FALSE
  )

  qpdf::pdf_combine(
    input = input,
    output = filename
  )

  fs::dir_delete(path)
}
