# Generated by staticimports; do not edit by hand.
# ======================================================================
# Imported from pkg:isstatic
# ======================================================================

#' Does string contain a filetype or the specified filetype?
#'
#' Check if string contains any filetype or the provided filetype. If string is
#' `NULL`, returns `FALSE`.
#'
#' @param string String to be tested with or without filetype. Defaults to
#'   `NULL`.
#' @param filetype File type to test against. Optional.
#' @param ignore.case If `FALSE`, the pattern matching is case sensitive. If
#'   `TRUE`, case is ignored.
#' @noRd
has_filetype <- function(string = NULL, filetype = NULL, ignore.case = FALSE) {
  if (is.null(string)) {
    return(FALSE)
  }

  if (is.null(filetype)) {
    filetype <- "[a-zA-Z0-9]+"
  }
  grepl(paste0("\\.", filetype, "$(?!\\.)"), string, ignore.case, perl = TRUE)
}

#' Do any items in a list or vector return TRUE from a predicate function?
#'
#' @param x A list or vector passed to [vapply()].
#' @param FUN Function passed to FUN parameter of [vapply()].
#' @noRd
is_any <- function(x, FUN) {
  any(vapply(x, FUN, FUN.VALUE = TRUE))
}

#' Is any item in a list or vector a NULL value?
#'
#' @param x A list or vector to check.
#' @noRd
is_any_null <- function(x) {
  is_any(x, is.null)
}
